### ISSUE TITLE
Bug: edges entering visually inside nodes

### ISSUE THREAD

**Issue by Oceanos1** [com-480-data-visualization/com-480-project-vizcachas#22]

**Comment by valentinoli** [comment]
@Oceanos1 We were right, and I don't know why it took me so long to understand what needed to be done. In the constructor, we created the node selection before the link selection. Reversing the order solves the issue. However, the nodes need to have zero transparency (`opacity: 1`), otherwise the edges can be seen through the nodes :)

**Comment by valentinoli** [comment]
This revealed another problem though, the arrowtips have a fixed position, and that doesn't work well with the different node sizes. We need to figure out how to fix that

![image](https://user-images.githubusercontent.com/23453691/82380805-5fcf9e00-9a29-11ea-8f97-138a962ba512.png)
